import type { TypeProduitDef } from '../types';

export const TYPES_PRODUITS: TypeProduitDef[] = [
  {
    id: 'fenetre',
    label: 'Fenêtre',
    description: 'Fenêtre sur mesure 1, 2 ou 3 vantaux',
    icon: 'SquareStack',
    materiauxDisponibles: ['pvc', 'bois', 'aluminium', 'bois_alu', 'pvc_alu'],
    formesDisponibles: ['rectangulaire', 'cintre', 'arc_surbaisse', 'trapeze', 'triangle', 'rond', 'oeil_de_boeuf'],
    ouverturesDisponibles: ['fixe', 'battant_gauche', 'battant_droit', 'oscillo_battant_gauche', 'oscillo_battant_droit', 'a_soufflet'],
    hasVitrage: true,
    hasVoletIntegre: true,
  },
  {
    id: 'porte_fenetre',
    label: 'Porte-fenêtre',
    description: 'Porte-fenêtre et baie vitrée battante ou coulissante',
    icon: 'DoorOpen',
    materiauxDisponibles: ['pvc', 'bois', 'aluminium', 'bois_alu', 'pvc_alu'],
    formesDisponibles: ['rectangulaire', 'cintre', 'arc_surbaisse'],
    ouverturesDisponibles: ['battant_gauche', 'battant_droit', 'oscillo_battant_gauche', 'oscillo_battant_droit', 'coulissant', 'oscillo_coulissant', 'soulevant_coulissant', 'galandage'],
    hasVitrage: true,
    hasVoletIntegre: true,
  },
  {
    id: 'baie_vitree',
    label: 'Baie vitrée',
    description: 'Grande baie vitrée coulissante ou à galandage',
    icon: 'PanelsTopLeft',
    materiauxDisponibles: ['pvc', 'aluminium', 'bois_alu'],
    formesDisponibles: ['rectangulaire'],
    ouverturesDisponibles: ['coulissant', 'oscillo_coulissant', 'soulevant_coulissant', 'galandage'],
    hasVitrage: true,
    hasVoletIntegre: true,
  },
  {
    id: 'porte_entree',
    label: "Porte d'entrée",
    description: "Porte d'entrée sur mesure, sécurisée et isolante",
    icon: 'DoorClosed',
    materiauxDisponibles: ['pvc', 'bois', 'aluminium', 'bois_alu'],
    formesDisponibles: ['rectangulaire', 'cintre', 'arc_surbaisse'],
    ouverturesDisponibles: ['battant_gauche', 'battant_droit'],
    hasVitrage: true,
    hasVoletIntegre: false,
  },
  {
    id: 'volet_roulant',
    label: 'Volet roulant',
    description: 'Volet roulant manuel ou motorisé, neuf ou rénovation',
    icon: 'Blinds',
    materiauxDisponibles: ['pvc', 'aluminium'],
    formesDisponibles: ['rectangulaire'],
    ouverturesDisponibles: [],
    hasVitrage: false,
    hasVoletIntegre: false,
  },
  {
    id: 'store',
    label: 'Store',
    description: 'Store intérieur ou extérieur, brise-soleil, store banne',
    icon: 'Sun',
    materiauxDisponibles: ['aluminium'],
    formesDisponibles: ['rectangulaire'],
    ouverturesDisponibles: [],
    hasVitrage: false,
    hasVoletIntegre: false,
  },
  {
    id: 'pergola',
    label: 'Pergola',
    description: 'Pergola bioclimatique, adossée ou autoportante',
    icon: 'Fence',
    materiauxDisponibles: ['aluminium'],
    formesDisponibles: ['rectangulaire'],
    ouverturesDisponibles: [],
    hasVitrage: false,
    hasVoletIntegre: false,
  },
  {
    id: 'portail',
    label: 'Portail',
    description: 'Portail battant ou coulissant, portillon',
    icon: 'Gate',
    materiauxDisponibles: ['aluminium', 'pvc'],
    formesDisponibles: ['rectangulaire'],
    ouverturesDisponibles: ['battant_gauche', 'battant_droit', 'coulissant'],
    hasVitrage: false,
    hasVoletIntegre: false,
  },
];

export function getTypeProduit(id: string): TypeProduitDef | undefined {
  return TYPES_PRODUITS.find((t) => t.id === id);
}
